### ISSUE TITLE
\dist\offline does not exists

### ISSUE THREAD

**Issue by guoguo0202** [steamerjs/ak-webpack-plugin#3]
I do it according to DEMO, but hint  \dist\offline does not exists

**Comment by lcxfs1991** [comment]
Could u provide your RTX id? I will chat with u internally.

**Comment by guoguo0202** [comment]
qq可以吗？ 464347881

**Comment by lili21** [comment]
run into same issue. keep telling me that `dist/offline` does not exists.

below is my config

```javascript
// webpack.config.js
...
  new AkWebpackPlugin({
    zpiFileName: 'dist/offline',
    src: 'dist'
  })
...
```

**Comment by lili21** [comment]
https://github.com/steamerjs/ak-webpack-plugin/blob/v3/index.js#L163

这个地方肯定要先创建这个destPath吧。

**Comment by lcxfs1991** [comment]
@lili21 遇到什么问题吗？

**Comment by lili21** [comment]
![image](https://user-images.githubusercontent.com/4456380/53538405-75b52280-3b48-11e9-8177-3083a9e6e39f.png)

**Comment by lili21** [comment]
我的描述里不是已经说了我遇到什么问题吗。

**Comment by lcxfs1991** [comment]
发个pr我merge一下？
